#!/usr/bin/python3

"""Uses PyDictionary to define words"""

import argparse
from enum import Enum
from PyDictionary import PyDictionary
dictionary = PyDictionary()

parser = argparse.ArgumentParser()
parser.add_argument('words', nargs='+')
parser.add_argument('--synonyms', '-s', action='store_true')
parser.add_argument('--antonyms', '-a', action='store_true')
parser.add_argument('--translate', '-t', default='')
args = parser.parse_args()

class color(Enum):
   Adverb = '\033[95m'
   Adjective = '\033[96m'
   Noun = '\033[92m'
   Verb = '\033[91m'
   BOLD = '\033[1m'
   END = '\033[0m'

for i in args.words:
    d = dictionary.meaning(i)
    print(color.BOLD.value + i + color.END.value)
    if d is not None:
        for k in d:
            print(color[k].value + k + color.END.value)
            print("\n".join(d[k]))
        print("")
    else:
        print("No definitions found")
    if args.synonyms:
        print("Synonyms: " + ", ".join(dictionary.synonym(i)))
    if args.antonyms:
        print("Antonyms: " + ", ".join(dictionary.antonym(i)))
    if args.translate:
        print("Translation to %s: %s" % (args.translate, dictionary.translate(i, args.translate)))
